In [4]:
import h5py
import librosa
import pydub # faster than librosa
import numpy      as np
import pandas     as pd
import time
#import tensorflow as tf
#from tensorflow.keras.layers.experimental import preprocessing

from pytorch.coughvid_dataset import CoughvidDataset
from torch.utils.data import DataLoader 
#import torchvision.models as models

In [5]:
dir = 'C:/COUGHVID_public_dataset/public_dataset/'

dataset = CoughvidDataset(dir, 'metadata_compiled.csv')

data = dataset.dataframe

# get only records that have a COVID status label and a cough-detected above 0.8. Loading all the files takes too long
status = np.isin(data['status'],[0,1,2])#['healthy','symptomatic','COVID-19'])
cough_detected = data['cough_detected'] > 0.8 # recommended threshold from https://www.nature.com/articles/s41597-021-00937-4

labelled_data = data[ np.logical_and(status,cough_detected) ]

dataset.dataframe = labelled_data

# load data
batch_size = 1
num_workers = 8
dataloader = DataLoader(dataset, num_workers=num_workers)#, batch_size=batch_size)

print(str(len(dataloader)) + " matching records found.")

# takes about 16 minutes
start = time.time()
all_data = [[audio,labels] for audio,labels in dataloader]
end = time.time()

print(f'{end-start} seconds elapsed.')

-0.22686290740966797 elapsed.
10817 matching records found.
-968.0128440856934 elapsed.


In [6]:
'''model = tf.keras.applications.resnet50.ResNet50(
    include_top=True, weights='imagenet', input_tensor=None,
    input_shape=None, pooling=None, classes=1000
)'''

all_data

[[tensor([[0, 0, 0,  ..., 0, 0, 0]]),
  tensor([[ 0.9609, 16.1514,  0.0000, 15.0000]])],
 [tensor([[       0,        0,        0,  ..., -1826094, -2826754, -3045855]]),
  tensor([[ 0.9301, 20.1461,  0.0000, 34.0000]])],
 [tensor([[     0,      0,      0,  ..., -11645,   1931,  -4736]]),
  tensor([[ 0.9968, 13.1465,  0.0000, 21.0000]])],
 [tensor([[    0,     0,     0,  ...,  9513,  1888, -3886]]),
  tensor([[ 0.8937, 13.4776,  0.0000, 28.0000]])],
 [tensor([[0, 0, 0,  ..., 0, 0, 0]]),
  tensor([[ 0.9883, 14.6039,  0.0000, 15.0000]])],
 [tensor([[      0,       0,       0,  ..., -106931,  -68151,  -37430]]),
  tensor([[ 1.0000,  9.6242,  1.0000, 35.0000]])],
 [tensor([[    0,     0,     0,  ..., 56751, 62357, 56887]]),
  tensor([[ 0.9959, 35.6418,  0.0000, 46.0000]])],
 [tensor([[      0,       0,       0,  ..., -142233, -181086, -116368]]),
  tensor([[ 0.8109, 15.6978,  0.0000, 39.0000]])],
 [tensor([[    0,     0,     0,  ...,  7169, 35113, 37873]]),
  tensor([[ 0.9794, 15.8700,  0.00